import type { ZudokuConfig } from "zudoku";

const config: ZudokuConfig = {
  theme: {
    // registryUrl: "https://tweakcn.com/r/themes/darkmatter.json",
  },
  site: {
    logo: {
      src: { light: "/logo-light.svg", dark: "/logo-dark.svg" },
      alt: "Дорога",
      width: "130px",
    },
  },
  docs: {
    files: "/pages/**/*.{md,mdx}",
  },
  navigation: [
    {
      type: "category",
      label: "Общее",
      items: [
        { type: "doc", file: "index", label: "Обзор" },
        { type: "doc", file: "architecture", label: "Архитектура системы" },
        { type: "doc", file: "integration-contract", label: "Интеграционный контракт" },
        { type: "doc", file: "backend-api", label: "Канонический Backend API" },
        { type: "doc", file: "database-entities", label: "Сущности БД" },
        { type: "doc", file: "frontend", label: "Frontend: каноническая карта" },
        { type: "doc", file: "inconsistencies", label: "Журнал расхождений" },
        { type: "doc", file: "documentation-rules", label: "Правила документации" },
        { type: "doc", file: "DOCS_STYLEGUIDE", label: "Style Guide" },
      ],
    },
    {
      type: "category",
      label: "Backend",
      items: [
        { type: "doc", file: "backend/index", label: "Обзор Backend" },
        { type: "doc", file: "backend/architecture", label: "Архитектура" },
        { type: "doc", file: "backend/api-guidelines", label: "API Guidelines" },
        { type: "doc", file: "backend/api-reference", label: "API Reference (REST)" },
        { type: "doc", file: "backend/coding-standards", label: "Coding Standards" },
        { type: "doc", file: "backend/testing-strategy", label: "Testing Strategy" },
        { type: "doc", file: "backend/seeding", label: "Seeding" },
        { type: "doc", file: "backend/repository-query-catalog", label: "Repository Query Catalog" },
        { type: "doc", file: "backend/runbook", label: "Runbook" },
        {
          type: "category",
          label: "Data Model",
          items: [
            { type: "doc", file: "backend/data-model", label: "Обзор" },
            { type: "doc", file: "backend/data-model/entities/branches", label: "branches" },
            { type: "doc", file: "backend/data-model/entities/change_log", label: "change_log" },
            { type: "doc", file: "backend/data-model/entities/direction_statuses", label: "direction_statuses" },
            { type: "doc", file: "backend/data-model/entities/conclusions", label: "conclusions" },
            { type: "doc", file: "backend/data-model/entities/directions", label: "directions" },
            { type: "doc", file: "backend/data-model/entities/doctors", label: "doctors" },
            { type: "doc", file: "backend/data-model/entities/indicators", label: "indicators" },
            { type: "doc", file: "backend/data-model/entities/labs", label: "labs" },
            { type: "doc", file: "backend/data-model/entities/objects", label: "objects" },
            { type: "doc", file: "backend/data-model/entities/protocol_types", label: "protocol_types" },
            { type: "doc", file: "backend/data-model/entities/protocols", label: "protocols" },
            { type: "doc", file: "backend/data-model/entities/permissions", label: "permissions" },
            { type: "doc", file: "backend/data-model/entities/research", label: "research" },
            { type: "doc", file: "backend/data-model/entities/research_goals", label: "research_goals" },
            { type: "doc", file: "backend/data-model/entities/research_statuses", label: "research_statuses" },
            { type: "doc", file: "backend/data-model/entities/role_permissions", label: "role_permissions" },
            { type: "doc", file: "backend/data-model/entities/roles", label: "roles" },
            { type: "doc", file: "backend/data-model/entities/sample_statuses", label: "sample_statuses" },
            { type: "doc", file: "backend/data-model/entities/sample_types", label: "sample_types" },
            { type: "doc", file: "backend/data-model/entities/samples", label: "samples" },
            { type: "doc", file: "backend/data-model/entities/test_statuses", label: "test_statuses" },
            { type: "doc", file: "backend/data-model/entities/tests", label: "tests" },
            { type: "doc", file: "backend/data-model/entities/user_scopes", label: "user_scopes" },
            { type: "doc", file: "backend/data-model/entities/users", label: "users" },
          ],
        },
        {
          type: "category",
          label: "DTO Contracts",
          items: [
            { type: "doc", file: "backend/dto-contracts", label: "Обзор" },
            { type: "doc", file: "backend/dto-contracts/frontend-auth-read-schema", label: "Auth Read Schema" },
            { type: "doc", file: "backend/dto-contracts/entities/index", label: "Индекс сущностей" },
            { type: "doc", file: "backend/dto-contracts/entities/branches", label: "branches" },
            { type: "doc", file: "backend/dto-contracts/entities/change_log", label: "change_log" },
            { type: "doc", file: "backend/dto-contracts/entities/direction_statuses", label: "direction_statuses" },
            { type: "doc", file: "backend/dto-contracts/entities/conclusions", label: "conclusions" },
            { type: "doc", file: "backend/dto-contracts/entities/directions", label: "directions" },
            { type: "doc", file: "backend/dto-contracts/entities/doctors", label: "doctors" },
            { type: "doc", file: "backend/dto-contracts/entities/indicators", label: "indicators" },
            { type: "doc", file: "backend/dto-contracts/entities/labs", label: "labs" },
            { type: "doc", file: "backend/dto-contracts/entities/objects", label: "objects" },
            { type: "doc", file: "backend/dto-contracts/entities/protocol_types", label: "protocol_types" },
            { type: "doc", file: "backend/dto-contracts/entities/protocols", label: "protocols" },
            { type: "doc", file: "backend/dto-contracts/entities/permissions", label: "permissions" },
            { type: "doc", file: "backend/dto-contracts/entities/research", label: "research" },
            { type: "doc", file: "backend/dto-contracts/entities/research_goals", label: "research_goals" },
            { type: "doc", file: "backend/dto-contracts/entities/research_statuses", label: "research_statuses" },
            { type: "doc", file: "backend/dto-contracts/entities/role_permissions", label: "role_permissions" },
            { type: "doc", file: "backend/dto-contracts/entities/roles", label: "roles" },
            { type: "doc", file: "backend/dto-contracts/entities/sample_statuses", label: "sample_statuses" },
            { type: "doc", file: "backend/dto-contracts/entities/sample_types", label: "sample_types" },
            { type: "doc", file: "backend/dto-contracts/entities/samples", label: "samples" },
            { type: "doc", file: "backend/dto-contracts/entities/test_statuses", label: "test_statuses" },
            { type: "doc", file: "backend/dto-contracts/entities/tests", label: "tests" },
            { type: "doc", file: "backend/dto-contracts/entities/user_scopes", label: "user_scopes" },
            { type: "doc", file: "backend/dto-contracts/entities/users", label: "users" },
          ],
        },
        {
          type: "category",
          label: "Reports",
          items: [
            { type: "doc", file: "backend/reports/index", label: "Index" },
            { type: "doc", file: "backend/reports/orm-query-plan-report-2026-02-19", label: "ORM Query Plan 2026-02-19" },
            { type: "doc", file: "backend/reports/total-count-optimization-2026-02-19", label: "Total Count Optimization 2026-02-19" },
            { type: "doc", file: "backend/reports/query-plan-index-verification-checklist", label: "Query Plan Index Verification Checklist" },
          ],
        },
        {
          type: "category",
          label: "ADR",
          items: [
            { type: "doc", file: "backend/adr/index", label: "Обзор" },
            { type: "doc", file: "backend/adr/ADR-0001-layered-architecture", label: "ADR-0001" },
            { type: "doc", file: "backend/adr/ADR-0002-uuidv7-soft-delete", label: "ADR-0002" },
            { type: "doc", file: "backend/adr/ADR-0003-rfc9457-error-format", label: "ADR-0003" },
            { type: "doc", file: "backend/adr/ADR-0004-pagination-filter-contract", label: "ADR-0004" },
            { type: "doc", file: "backend/adr/ADR-0005-unified-dto-contracts", label: "ADR-0005" },
            { type: "doc", file: "backend/adr/ADR-0006-jwt-cookie-auth", label: "ADR-0006" },
            { type: "doc", file: "backend/adr/ADR-0007-rbac-scope-permissions-model", label: "ADR-0007" },
          ],
        },
        {
          type: "category",
          label: "User Guide",
          items: [
            { type: "doc", file: "backend/user-guide/index", label: "Руководство пользователя" },
            { type: "doc", file: "backend/user-guide/roles-and-permissions", label: "Роли и права" },
            { type: "doc", file: "backend/user-guide/directions-and-samples", label: "Работа с направлениями и образцами" },
            { type: "doc", file: "backend/user-guide/excel-import", label: "Импорт из Excel" },
            { type: "doc", file: "backend/user-guide/results-protocols-conclusions", label: "Исследования, протоколы, заключения" },
            { type: "doc", file: "backend/user-guide/faq", label: "FAQ" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Frontend",
      items: [
        { type: "doc", file: "frontend/index", label: "Обзор Frontend" },
        { type: "doc", file: "frontend/getting-started", label: "Быстрый старт" },
        { type: "doc", file: "frontend/project/current-state", label: "Текущее состояние" },
        { type: "doc", file: "frontend/api-spec", label: "API Spec" },
        {
          type: "category",
          label: "Architecture",
          items: [
            { type: "doc", file: "frontend/architecture/overview", label: "Overview" },
            { type: "doc", file: "frontend/architecture/project-structure", label: "Project Structure" },
            { type: "doc", file: "frontend/architecture/router-and-guards", label: "Router and Guards" },
            { type: "doc", file: "frontend/architecture/auth-and-permissions", label: "Auth and Permissions" },
          ],
        },
        {
          type: "category",
          label: "Modules",
          items: [
            { type: "doc", file: "frontend/modules/overview", label: "Overview" },
            { type: "doc", file: "frontend/modules/catalog-modules", label: "Catalog Modules" },
            { type: "doc", file: "frontend/modules/objects", label: "Objects" },
            { type: "doc", file: "frontend/modules/roles-and-permissions", label: "Roles and Permissions" },
            { type: "doc", file: "frontend/modules/admin-users", label: "Admin Users" },
          ],
        },
        {
          type: "category",
          label: "API",
          items: [
            { type: "doc", file: "frontend/api/overview", label: "Overview" },
            { type: "doc", file: "frontend/api/modules-contracts", label: "Modules Contracts" },
            { type: "doc", file: "frontend/api/openapi-fastapi", label: "OpenAPI FastAPI" },
          ],
        },
        {
          type: "category",
          label: "UI and Shared",
          items: [
            { type: "doc", file: "frontend/ui/base-components", label: "Base Components" },
            { type: "doc", file: "frontend/composables/core-composables", label: "Core Composables" },
          ],
        },
        {
          type: "category",
          label: "Testing and Ops",
          items: [
            { type: "doc", file: "frontend/testing/e2e", label: "E2E Testing" },
            { type: "doc", file: "frontend/mock/mock-server", label: "Mock Server" },
            { type: "doc", file: "frontend/operations/troubleshooting", label: "Troubleshooting" },
          ],
        },
        { type: "doc", file: "frontend/guides/add-crud-module", label: "Guide: Add CRUD Module" },
      ],
    },
    {
      type: "link",
      to: "/api",
      label: "API Reference",
    },
  ],

  redirects: [{ from: "/", to: "/index" }],

  apis: {
    type: "file",
    input: "./apis/openapi.json",
    path: "/api",
    options: {
      examplesLanguage: "shell",
      supportedLanguages: [
        { label: "cURL", value: "shell" },
        { label: "JavaScript", value: "javascript" },
        { label: "Python", value: "python" },
      ],
      disablePlayground: false,
      disableSidecar: false,
      showVersionSelect: "always",
      expandAllTags: true,
      expandApiInformation: false,
      schemaDownload: { enabled: true },
    },
  },
};

export default config;
